name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features and Improvements"
    labels:
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
  - title: "📚 Documentation"
    labels:
      - "documentation"
change-template: "- $TITLE (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "bump-major"
      - "breaking"
  minor:
    labels:
      - "bump-minor"
      - "enhancement"
  default: patch
template: |
  ## What's Changed
  $CHANGES

exclude-labels:
  - "skip-release-notes"
