name: 'Text Variables'
description:
  'Load a text file and replace Nunjucks style variables. Returns modified text
  as an output for use in other actions.'
author: 'GitHub'

inputs:
  # Pick a source for the template text.
  template-file:
    description: 'The path to a text file to load as the template.'
    required: false
  template-text:
    description:
      'The template text with variable placeholders. Disables loading from file.'
    required: false

  # Replace variables using JSON.
  template-vars:
    description: 'A JSON object containing variables to replace in the text.'
    required: true

outputs:
  updated-text:
    description: 'The text content with variables replaced.'

runs:
  using: node20
  main: dist/index.js
