# Header levels should only increment by one level at a time
MD01: false

# Unordered list style
MD004:
  style: dash

# Line length
MD013:
  tables: false

# Allow bare URLs
MD034: false

# Trailing punctuation in heading
MD026:
  punctuation: '.,;:!'

# Ordered list item prefix
MD029:
  style: one

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# First line in a file should be a top-level heading
MD041: false

# Code block style
MD046:
  style: fenced
